# Generated by Django 6.0 on 2025-12-27 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app1", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="programregistration",
            name="status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("active", "Active"),
                    ("cancel_requested", "Cancel Requested"),
                    ("cancelled", "Cancelled"),
                ],
                default="active",
                max_length=20,
                null=True,
            ),
        ),
    ]
