# Generated by Django 6.0 on 2025-12-27 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app1", "0002_programregistration_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="programregistration",
            name="first_place",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="programregistration",
            name="result_published",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="programregistration",
            name="second_place",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="programregistration",
            name="third_place",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
