# Generated by Django 6.0 on 2026-01-27 19:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app1", "0006_admin"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="event",
            name="category",
        ),
    ]
